name: mlflow_mockup
channels:
  - defaults
dependencies:
  - pip
  - python=3.7
  - scikit-learn
  - pandas
  - s3fs
  - joblib
  - lightgbm
  - pyyaml
  - pyarrow
  # - psutil --> for modin
  # - distributed --> for modin
  - pip:
      - mlflow>=1.3
      - neptune-client
      # - modin[ray]
