name: mlflow_mockup
channels:
  - defaults
dependencies:
  - pip
  - python=3.7
  - scikit-learn
  - pandas
  - s3fs
  - joblib
  - lightgbm
  - pyyaml
  - pyarrow
  - psutil
  - distributed
  - pip:
      - modin[ray]
      - mlflow>=1.3
